//Posts

GET http://localhost:5000/api/posts HTTP/1.1

###

GET http://localhost:5000/api/posts/5 HTTP/1.1

###

DELETE http://localhost:5000/api/posts/37 HTTP/1.1

###

PUT http://localhost:5000/api/posts/2 HTTP/1.1
content-type: application/json

{
    "text": "A wizard is never late, Frodo Baggins. Nor is he early. He arrives precisely when he means to.",
    "user_id": 1
}

###

POST http://localhost:5000/api/posts/1/comments HTTP/1.1
content-type: application/json

{
    "text": "You can not hide, I see you! There is no life, after me. Only!.. Death!"
}

###

GET http://localhost:5000/api/posts/1/comments HTTP/1.1

###

DELETE http://localhost:5000/api/posts/11 HTTP/1.1

###

PUT http://localhost:5000/api/posts/10 HTTP/1.1
content-type: application/json

{
    "title": "I think we should get off the road. Get off the road! Quick!",
    "contents": "Not the beard!"
}